# Generated by Django 2.0.3 on 2018-03-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebedero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30)),
                ('rango_usuarios', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='bebederos')),
                ('peso', models.IntegerField()),
                ('dimensiones', models.CharField(max_length=30)),
            ],
        ),
    ]
