# Generated by Django 2.0.3 on 2018-03-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bebedero',
            old_name='dimensiones',
            new_name='nivel_educativo',
        ),
        migrations.RemoveField(
            model_name='bebedero',
            name='peso',
        ),
    ]
