# Generated by Django 2.0.3 on 2018-03-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebederos', '0002_auto_20180316_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebedero',
            name='nivel_educativo',
            field=models.CharField(choices=[('Preescolar', 'Preescolar'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], max_length=30),
        ),
    ]
